service: serverless-nodejs-template

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  helloWorld:
    handler: src/handler.helloWorld
