service: serverless-nodejs-template

frameworkVersion: '2'

variablesResolutionMode: 20210326 # enable complete support for "ssm" variables resolution. If no resolution is found during deployment, error is thrown.
useDotenv: false # Should not be used.
unresolvedVariablesNotificationMode: error # Error thrown if any variables expected can not be resolved

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  helloWorld:
    handler: src/handler.helloWorld
